<%@ Page Language="C#" MasterPageFile="~/Admin_Master.master" AutoEventWireup="true" CodeFile="View_city.aspx.cs" Inherits="View_city" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table width="100%">
<tr>
<td colspan="2" align="center">
<asp:Label ID="lblheader" runat="server" Text="View City From Here" 
        Font-Bold="True" Font-Size="Medium" ForeColor="Blue" Font-Underline="True"></asp:Label>
</td>
</tr>
<tr>
<td align="center">
<asp:GridView ID="grvcity" runat="server" Width="100%" AutoGenerateColumns="False" 
        BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" 
        CellPadding="3" CellSpacing="1" DataSourceID="SqlDataSource1" 
        DataKeyNames="cid" GridLines="None" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" EmptyDataText="Currently No Data Available!">
    <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
    <Columns>
        <asp:BoundField DataField="cid" HeaderText="cid" InsertVisible="False" 
            ReadOnly="True" SortExpression="cid" Visible="false" />
        <asp:BoundField DataField="cname" HeaderText="City Name" SortExpression="cname" />
    </Columns>
    <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
    <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
    <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
    <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        SelectCommand="SELECT * FROM [tbl_city]" DeleteCommand="Delete from tbl_city where cid=@cid" UpdateCommand="Update tbl_city set cname=@cname where cid=@cid"></asp:SqlDataSource>
</td>
</tr>
</table>
</asp:Content>

